#!/usr/bin/env bash
# Copies a file to a server from a client.

if ["$#" -lt 3]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
echo
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
