#!/usr/bin/env bash
# Copies a file to a server from a client.

if [ "$#" -eq 4 ]; then
    scp -o StrictHostKeyChecking=no -i "$4"  "$1" "$3@$2:~"
elif [ "$#" -eq 3 ]; then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi
