#!/usr/bin/env bash
# Copies a file to a server from a client.

msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ "$4" ]; then
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [ "$3" ]; then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "$msg";
fi
