#!/usr/bin/env bash
# Configure nginx for redirection 301.

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
