#!/usr/bin/env bash
# Configure nginx for redirection 404 not found.

apt -y update
apt -y install nginx
chown -R ubuntu /var/www
echo "Ceci n'est pas une page" > /var/www/html/404.html
newinput="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "29i $newinput" /etc/nginx/sites-available/default
service nginx restart
