#!/usr/bin/env bash
# Configure nginx for redirection 404.

sudo apt -y update
sudo apt -y install nginx
sudo chown -R ubuntu /var/www
echo "Ceci n'est pas une page" > /var/www/html/404.html
newinput="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "29i $newinput" /etc/nginx/sites-available/default
sudo service nginx restart
